CREATE TABLE TBL_BOARD(
	BOARD_ID INT NOT NULL AUTO_INCREMENT,
	SUBJECT VARCHAR(200) NOT NULL,
	CONTENT TEXT NULL,
	WRITER VARCHAR(50) NOT NULL,
	REGISTER_DATE timestamp default now(),
	HIT INT DEFAULT 0,
    primary key(BOARD_ID)
)